import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { faker } from '@faker-js/faker';
import bcrypt from 'bcryptjs';
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import PDFDocument from 'pdfkit';

import User from './models/User.js';
import Patient from './models/Patient.js';
import Report from './models/Report.js';

// Load env vars
dotenv.config({ path: '../.env' }); // Fallback if run from server folder
dotenv.config({ path: '.env' }); // Fallback if run from root folder

// --- DATA ARRAYS ---
const TAMIL_MALE_NAMES = [
    'Arun', 'Balaji', 'Karthik', 'Suresh', 'Ramesh', 'Vijay', 'Ajith', 'Surya', 'Dhanush', 'Vikram',
    'Siva', 'Prabhu', 'Goutham', 'Murali', 'Vignesh', 'Prasanth', 'Hari', 'Manoj', 'Saravanan',
    'Senthil', 'Murugan', 'Velu', 'Selvam', 'Anbu', 'Elango', 'Gopi', 'Praveen', 'Rajasekar', 'Aari'
];

const TAMIL_FEMALE_NAMES = [
    'Priya', 'Kavitha', 'Lakshmi', 'Nithya', 'Swathi', 'Divya', 'Anitha', 'Revathi', 'Meena',
    'Geetha', 'Saritha', 'Bhavani', 'Gomathi', 'Vidhya', 'Sandhya', 'Sneha', 'Trisha', 'Nayanthara',
    'Shruti', 'Valli', 'Malar', 'Kani', 'Amala', 'Nandhini', 'Sindhu', 'Keerthi', 'Yamini'
];

const TAMIL_LAST_NAMES = [
    'Kumar', 'Raj', 'Krishnan', 'Pillai', 'Iyer', 'Chettiar', 'Gounder', 'Nadar', 'Thevar',
    'Reddy', 'Naidu', 'Raman', 'Sundaram', 'Swamy', 'Narayanan', 'Murugan', 'Balasubramanian',
    'Chandran', 'Rangan', 'Pandian', 'Prasad', 'Rao'
];

const TN_DISTRICTS = [
    'Chennai', 'Madurai', 'Coimbatore', 'Trichy', 'Salem', 'Tirunelveli', 'Erode',
    'Vellore', 'Thanjavur', 'Tiruppur', 'Dindigul', 'Karur', 'Kanyakumari', 'Thoothukudi'
];

const DOCTOR_SPECIALIZATIONS = [
    "General Medicine", "Internal Medicine", "Neurology", "Neurosurgery",
    "Psychiatry", "Cardiology", "Cardiothoracic Surgery", "Orthopedics",
    "Rheumatology", "Pediatrics", "Pediatric Surgery", "Gynecology",
    "Obstetrics", "Endocrinology", "Gastroenterology", "Nephrology",
    "Pulmonology", "Hematology", "Oncology", "Ophthalmology",
    "ENT", "Dermatology", "Dentistry", "Emergency Medicine", "Anesthesiology"
];
const LAB_SPECIALIZATIONS = ['MRI', 'Blood Test', 'CT Scan', 'X-Ray', 'Ultrasound'];
const REPORT_CATEGORIES = ['Blood Test', 'MRI', 'CT Scan', 'X-Ray', 'Ultrasound', 'Other'];

// --- HELPERS ---
const getRandomTamilName = () => {
    const isMale = faker.datatype.boolean();
    const firstName = isMale ? faker.helpers.arrayElement(TAMIL_MALE_NAMES) : faker.helpers.arrayElement(TAMIL_FEMALE_NAMES);
    const lastName = faker.helpers.arrayElement(TAMIL_LAST_NAMES);
    return `${firstName} ${lastName}`;
};

const getRandomDistrict = () => faker.helpers.arrayElement(TN_DISTRICTS);

// Generate PDF
const generateOriginalPDF = (filename, patient, category, doctor, technician, testDate) => {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 50 });
            const filePath = path.join(process.cwd(), 'server', 'uploads', filename); // Ensure it is created in server/uploads

            // Ensure dir exists
            const dir = path.dirname(filePath);
            if (!fs.existsSync(dir)) {
                fs.mkdirSync(dir, { recursive: true });
            }

            const stream = fs.createWriteStream(filePath);
            doc.pipe(stream);

            doc.fontSize(20).text(`HDAMS - Medical Diagnostic Report`, { align: 'center' });
            doc.moveDown();

            doc.fontSize(16).text(`${category} Report`, { align: 'center', underline: true });
            doc.moveDown(2);

            doc.fontSize(12).text(`Patient Name: ${patient.fullName}`);
            doc.text(`Medical Record Number: ${patient.medicalRecordNumber}`);
            doc.text(`Age/DOB: ${new Date(patient.dateOfBirth).toLocaleDateString()}`);
            doc.text(`Gender: ${patient.gender}`);
            doc.text(`Contact: ${patient.contactNumber}`);
            doc.moveDown();

            doc.text(`Assigned Doctor: ${doctor.name || patient.doctorName}`);
            doc.text(`Lab Technician: ${technician.name}`);
            doc.text(`Test Date: ${new Date(testDate).toLocaleString()}`);
            doc.moveDown();

            doc.fontSize(14).text('Diagnostic Findings:', { underline: true });
            doc.moveDown();
            doc.fontSize(12).text(faker.lorem.paragraphs(2));

            doc.moveDown(3);
            doc.text(`--- End of Report ---`, { align: 'center' });
            doc.text(`Electronically generated by MediVault DAM System`, { align: 'center', fontSize: 10, color: 'gray' });

            doc.end();

            stream.on('finish', () => resolve(filePath));
            stream.on('error', reject);
        } catch (error) {
            reject(error);
        }
    });
};

// --- SEED FUNCTION ---
const seedDatabase = async () => {
    try {
        // Connect to MongoDB
        const uri = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/hdmas';
        await mongoose.connect(uri);
        console.log(`✅ MongoDB Connected successfully to database!`);

        // Create a single shared password hash for optimal performance
        console.log('Generating password hashes (password123)...');
        const salt = await bcrypt.genSalt(10);
        const hashedPassword = await bcrypt.hash('password123', salt);

        // ============================================
        // 1. DOCTORS (50)
        // ============================================
        console.log('⏳ Seeding 50 Doctors...');
        const doctorsToInsert = [];
        for (let i = 0; i < 50; i++) {
            const name = getRandomTamilName();
            const spec = faker.helpers.arrayElement(DOCTOR_SPECIALIZATIONS);
            doctorsToInsert.push({
                name: `Dr. ${name}`,
                email: `dr.${name.toLowerCase().replace(/\s/g, '.')}${i}@hospital.com`,
                password: hashedPassword,
                role: 'doctor',
                specialization: spec,
                department: spec,
                contactNumber: faker.phone.number({ style: 'national' }),
                isActive: true,
                createdAt: faker.date.past({ years: 2 })
            });
        }
        // Using insertMany avoids the 'pre' save hook so we pre-hash the password
        const doctors = await User.insertMany(doctorsToInsert, { lean: true, ordered: false }).catch(err => {
            console.warn('Some doctors might be duplicates, inserting what we can.');
            return err.insertedDocs || User.find({ role: 'doctor' }).limit(50);
        });
        console.log(`✅ Doctors stage completed.`);

        // ============================================
        // 2. LAB TECHNICIANS (20)
        // ============================================
        console.log('⏳ Seeding 20 Lab Technicians...');
        const techsToInsert = [];
        for (let i = 0; i < 20; i++) {
            const name = getRandomTamilName();
            const spec = faker.helpers.arrayElement(LAB_SPECIALIZATIONS);
            techsToInsert.push({
                name: name,
                email: `tech.${name.toLowerCase().replace(/\s/g, '.')}${i}@hospital.com`,
                password: hashedPassword,
                role: 'technician',
                specialization: spec,
                department: `${spec} Department`,
                contactNumber: faker.phone.number({ style: 'national' }),
                isActive: true,
                createdAt: faker.date.past({ years: 2 })
            });
        }
        const technicians = await User.insertMany(techsToInsert, { lean: true, ordered: false }).catch(err => {
            console.warn('Some technicians might be duplicates, continuing.');
            return err.insertedDocs || User.find({ role: 'technician' }).limit(20);
        });
        console.log(`✅ Lab Technicians stage completed.`);

        // ============================================
        // 3. RECEPTIONISTS (10)
        // ============================================
        console.log('⏳ Seeding 10 Receptionists...');
        const receptionistsToInsert = [];
        for (let i = 0; i < 10; i++) {
            const name = getRandomTamilName();
            receptionistsToInsert.push({
                name: name,
                email: `rec.${name.toLowerCase().replace(/\s/g, '.')}${i}@hospital.com`,
                password: hashedPassword,
                role: 'receptionist',
                department: 'Front Desk',
                contactNumber: faker.phone.number({ style: 'national' }),
                isActive: true,
                createdAt: faker.date.past({ years: 2 })
            });
        }
        const receptionists = await User.insertMany(receptionistsToInsert, { lean: true, ordered: false }).catch(err => {
            console.warn('Some receptionists might be duplicates, continuing.');
            return err.insertedDocs || User.find({ role: 'receptionist' }).limit(10);
        });
        console.log(`✅ Receptionists stage completed.`);

        // ============================================
        // 4. PATIENTS (2000)
        // ============================================
        console.log('⏳ Seeding 2000 Patients...');
        const patientsToInsert = [];
        const MRN_YEAR = new Date().getFullYear();
        let currentPatientCount = await Patient.countDocuments(); // Ensure distinct MRN starting point

        for (let i = 0; i < 2000; i++) {
            const name = getRandomTamilName();
            const mrn = `MRN${MRN_YEAR}${String(currentPatientCount + i + 1).padStart(6, '0')}`;
            const assignedDoc = faker.helpers.arrayElement(doctors);

            patientsToInsert.push({
                medicalRecordNumber: mrn,
                fullName: name,
                dateOfBirth: faker.date.birthdate({ min: 5, max: 90, mode: 'age' }),
                gender: faker.helpers.arrayElement(['Male', 'Female']),
                address: `${faker.location.streetAddress()}, ${getRandomDistrict()}, Tamil Nadu`,
                contactNumber: faker.phone.number({ style: 'national' }),
                email: `${name.toLowerCase().replace(/\s/g, '')}${faker.number.int({ min: 10, max: 999 })}@example.com`,
                bloodGroup: faker.helpers.arrayElement(['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-']),
                assignedDoctor: assignedDoc._id,
                doctorName: assignedDoc.name,
                admissionStatus: faker.helpers.arrayElement(['In-Patient', 'Out-Patient', 'Discharged']),
                lastVisit: faker.date.recent({ days: 100 }),
                createdAt: faker.date.past({ years: 2 })
            });
        }
        // Ordered: false means if one fails, others continue inserting.
        const patients = await Patient.insertMany(patientsToInsert, { ordered: false });
        console.log(`✅ 2000 Patients inserted.`);

        // ============================================
        // 5. ORIGINAL REPORTS & PDFs (5000)
        // ============================================
        console.log('⏳ Seeding 5000 Reports and generating ORIGINAL PDF files. This will take a few minutes...');
        const CHUNK_SIZE = 100; // Smaller chunk for PDF I/O

        let totalReportsInserted = 0;

        for (let chunkIdx = 0; chunkIdx < Math.ceil(5000 / CHUNK_SIZE); chunkIdx++) {
            const reportsToInsert = [];

            // Collect the promises to generate PDFs for this chunk
            const pdfPromises = [];

            for (let i = 0; i < CHUNK_SIZE; i++) {
                const globalIdx = (chunkIdx * CHUNK_SIZE) + i;
                if (globalIdx >= 5000) break;

                const patient = faker.helpers.arrayElement(patients);
                const uploadedBy = faker.helpers.arrayElement(technicians);
                const category = faker.helpers.arrayElement(REPORT_CATEGORIES);
                const testDate = faker.date.recent({ days: 180 });
                const doctor = doctors.find(d => d._id.toString() === patient.assignedDoctor.toString()) || doctors[0];

                const filename = `report_${patient.medicalRecordNumber}_${Date.now()}_${globalIdx}.pdf`;
                const relativePath = `server/uploads/${filename}`;

                // Push to DB Array
                reportsToInsert.push({
                    patient: patient._id,
                    uploadedBy: uploadedBy._id,
                    assignedDoctor: patient.assignedDoctor,
                    title: `${patient.fullName} - ${category} Report`,
                    description: `This is an original generated ${category} medical report for patient ${patient.fullName}.`,
                    filePath: relativePath,
                    fileType: 'application/pdf',
                    fileSize: 15240, // Estimated rough size for small PDF
                    fileCategory: category,
                    visibility: 'private',
                    status: faker.helpers.arrayElement(['Pending Review', 'Reviewed', 'Final']),
                    isProtected: true,
                    secureToken: crypto.randomBytes(32).toString('hex') + `_${globalIdx}`,
                    testDate: testDate,
                    createdAt: testDate,
                    uploadDate: testDate
                });

                // Generate actual File
                pdfPromises.push(generateOriginalPDF(filename, patient, category, doctor, uploadedBy, testDate));
            }

            // Await PDF creations for this chunk
            await Promise.all(pdfPromises);

            // Insert reports into mongo
            await Report.insertMany(reportsToInsert, { ordered: false, lean: true });

            totalReportsInserted += reportsToInsert.length;
            console.log(`   ...inserted ${totalReportsInserted}/5000 original reports and PDFs generated.`);
        }

        console.log(`✅ 5000 Original Reports inserted and PDFs created successfully!`);

        console.log('\n🎉 ORIGINAL SEEDING COMPLETED SUCCESSFULLY! 🎉');
        process.exit(0);
    } catch (error) {
        console.error('\n❌ SEEDING FAILED:');
        console.error(error);
        process.exit(1);
    }
};

seedDatabase();

